---
title: "NBALinearRegression"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Data input }

seasons.stats = read.csv(file = "../data/Seasons_Stats.csv", header = TRUE)
head(seasons.stats)

```


```{r}

library(tidyverse) # sluzi za grupiranja, joinove, filtriranja

# plotting average points per year through all seasons
seasons.stats %>% group_by(Year) %>% summarize(avg.PTS = mean(PTS)) -> average.points
average.points
plot(average.points, xlab = "Year", ylab = "Average points")

# plotting average three and two point attempts per year
season.stats.points = seasons.stats[c('Year', 'X3PA', 'X2PA', 'G')]

season.stats.points$X3PAPerGame = season.stats.points$X3PA / season.stats.points$G
season.stats.points$X2PAPerGame = season.stats.points$X2PA / season.stats.points$G
season.stats.points.complete = season.stats.points[complete.cases(season.stats.points),]

season.stats.points.complete %>% group_by(Year) %>% summarize(ThreePointAttempts = mean(X3PAPerGame)) -> three.point.attempts
season.stats.points.complete %>% group_by(Year) %>% summarize(TwoPointAttempts = mean(X2PAPerGame)) -> two.point.attempts

three.point.attempts
two.point.attempts

# plotting three and two point attempts through the years
plot(
  three.point.attempts$Year, 
  three.point.attempts$ThreePointAttempts, 
  xlim = c(min(three.point.attempts$Year), max(three.point.attempts$Year)),
  ylim = c(min(three.point.attempts$ThreePointAttempts), max(three.point.attempts$ThreePointAttempts)),
  xlab = "Year",
  ylab = "3PA per game",
  col = 'blue'
)

three.point.attempts
test.data = three.point.attempts[three.point.attempts$Year > 2010,]
three.point.attempts = three.point.attempts[three.point.attempts$Year <= 2010,]

fit = lm(ThreePointAttempts~Year, data=three.point.attempts)
summary(fit)

fit$coefficients
plot(three.point.attempts$Year, three.point.attempts$ThreePointAttempts)
lines(three.point.attempts$Year, fit$fitted.values, col='skyblue')

plot(fit$residuals)

qqnorm(rstandard(fit))
qqline(rstandard(fit))

ks.test(rstandard(fit),'pnorm')

prediction = predict(fit,data=test.data, interval = "confidence")
prediction

actual <- data.frame(cbind(actuals=three.point.attempts$ThreePointAttempts, predicteds=prediction))
actual
```

